version: "3"
services: 
  api: 
    restart: always
    build:  "./api"
    container_name: "django-api"
    volumes: 
      - ./api:/api
    ports: 
      - 8000:8000
    image: "okakyo/django-api"
    depends_on: 
      - "db"
    command: ["sh","-c","python manage.py runserver 0.0.0.0:8000"]

  db:
    image: mysql:5.7
    container_name: main_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33069:3306
    
